<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Seeder;

class table_utilisateurs extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("utilisateurs")->insert([
            [
                "username"=>"lamacompta",
                "email"=>"rh@lamacompta.co",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"tgs",
                "email"=>"recrutement@tgs-france.fr",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"iadvize",
                "email"=>"join-us@iadvize.com",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"rubato",
                "email"=>"rh@rubato.fr",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"kissmy",
                "email"=>"kiss@kissmy.co",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"lengow",
                "email"=>"recruit@lengow.com",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"microsoft",
                "email"=>"career@microsoft.com",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"sensiolabs",
                "email"=>"join@sensiolabs.com",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"crisp",
                "email"=>"rh@crisp.chat",
                "password"=>"Motdepasse",
                "statut"=>"Entreprise"
            ],
            [
                "username"=>"jean-eudesroger",
                "email"=>"jean-eudes@gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"zakariabichon",
                "email"=>"zakariadu44gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"marieangelabranche",
                "email"=>"marie-ange@free.fr",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"geraldinedemonaco",
                "email"=>"geraldine@monaco.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"matuidicharo",
                "email"=>"charo.matuidi@gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"mateoguoge",
                "email"=>"matguoge@gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"mohamedramtah",
                "email"=>"mohamed@gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"leslieleroux",
                "email"=>"leslie@gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"salmaadjamagbo",
                "email"=>"salma@gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"audreybrullon",
                "email"=>"audreybrullon@gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"jasonfouasson",
                "email"=>"jasonfouasson@gmail;COM",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"killianleroux",
                "email"=>"killian@lamacompta.co",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"fabienpotencier",
                "email"=>"fabienyear@symfony.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"rasmuslerdord",
                "email"=>"lesdorf@msn.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"evanyou",
                "email"=>"evant.you@vue.js",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"kevindunglas",
                "email"=>"dunglas@gmail.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"brendaneich",
                "email"=>"brendan-eich@outlook.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"billgates",
                "email"=>"bill@gates.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"elonmush",
                "email"=>"elon.mush@yahoo.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"fereoljob",
                "email"=>"job.fereol@email.com",
                "password"=>"Motdepasse",
                "statut"=>"Candidat"
            ],
            [
                "username"=>"Admin",
                "email"=>"admin@email.com",
                "password"=>"Admin",
                "statut"=>"Admin"
            ]
        ]);
    }
}
